using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using eInvWorld.Data;
using eInvWorld.Services;
using eInvWorld.Models.Settings;
using eInvWorld.Models.Audit;
using eInvWorld.Models;
using Microsoft.Extensions.Options;

public class InvoiceFinalizerService : BackgroundService
{
    private readonly IServiceScopeFactory _serviceScopeFactory;
    private readonly ILogger<InvoiceFinalizerService> _logger;
    private readonly FilePathConfig _filePathConfig;
    private readonly int _intervalSeconds;

    public InvoiceFinalizerService(IServiceScopeFactory serviceScopeFactory, ILogger<InvoiceFinalizerService> logger, IOptions<FilePathConfig> filePathOptions, int intervalSeconds = 300)
    {
        _serviceScopeFactory = serviceScopeFactory;
        _logger = logger;
        _filePathConfig = filePathOptions.Value;
        _intervalSeconds = intervalSeconds;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Invoice Finalizer Service started...");
        _logger.LogWarning("InvoiceFinalizerService heartbeat at {Time}", DateTime.Now);

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                using var scope = _serviceScopeFactory.CreateScope();
                var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
                var pdfService = scope.ServiceProvider.GetRequiredService<PDFGeneratorService>();
                var notificationService = scope.ServiceProvider.GetRequiredService<EInvoiceNotificationService>();

                await FinalizeInvoicesAsync(dbContext, pdfService, notificationService);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "InvoiceFinalizerService encountered an error");
            }

            await Task.Delay(TimeSpan.FromSeconds(_intervalSeconds), stoppingToken);
        }
    }

    private async Task<InvoiceSyncResult> FinalizeInvoicesAsync(
        ApplicationDbContext dbContext,
        IPdfGeneratorService pdfService,
        IEInvoiceNotificationService notificationService)
    {
        var result = new InvoiceSyncResult();
        var graceCutoff = DateTime.Now.AddMinutes(-10);

        var invoices = await dbContext.InvoiceHeaders
            .Include(i => i.Customer)
            .Include(i => i.Supplier)
            .Where(i =>
                i.LHDNStatusId == "Valid" &&
                !string.IsNullOrWhiteSpace(i.LongId) &&
                i.DateTimeValidated != null &&
                i.DateTimeValidated <= graceCutoff &&
                (!i.IsPdfGenerated || !i.IsValidationEmailSent))
            .ToListAsync();

        foreach (var invoice in invoices)
        {
            bool changesMade = false;
            string pdfPath = Path.Combine(_filePathConfig.GeneratedPdfFolder, $"{invoice.InvoiceNo}.pdf");

            // ✅ Generate PDF if missing
            if (!invoice.IsPdfGenerated || !File.Exists(pdfPath))
            {
                try
                {
                    _logger.LogInformation($"📄 Generating PDF for invoice {invoice.InvoiceNo}...");
                    await pdfService.GeneratePdfAsync(invoice.InvoiceNo);
                    invoice.IsPdfGenerated = true;
                    invoice.PdfGeneratedAt = DateTime.Now;

                    dbContext.InvoiceHistories.Add(new InvoiceHistory
                    {
                        InvoiceNo = invoice.InvoiceNo,
                        Action = "PDFGenerated",
                        PerformedBy = "Finalizer",
                        Remarks = "Regenerated by Finalizer",
                        Timestamp = DateTime.UtcNow
                    });

                    result.PdfsGenerated++;
                    changesMade = true;
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"❌ Failed to generate PDF for {invoice.InvoiceNo}");
                }
            }

            // ⚠️ If PDF was deleted after email
            if (invoice.IsValidationEmailSent && !File.Exists(pdfPath))
            {
                _logger.LogWarning($"⚠️ PDF for invoice {invoice.InvoiceNo} missing after email sent. No resend.");
            }

            // ✅ Send email if not yet sent and PDF exists
            if (!invoice.IsValidationEmailSent && File.Exists(pdfPath))
            {
                try
                {
                    _logger.LogInformation($"📧 Sending email for invoice {invoice.InvoiceNo}");

                    await notificationService.SendValidatedNotificationEmail(
                        invoice.Customer?.CompanyName ?? "Customer",
                        invoice.Customer,
                        invoice.Supplier,
                        invoice.InvoiceNo,
                        invoice.IssueDate ?? DateTime.Now,
                        invoice.DateTimeValidated ?? DateTime.Now);

                    invoice.IsValidationEmailSent = true;
                    invoice.ValidationEmailSentAt = DateTime.Now;
                    invoice.ValidationEmailSentTo = string.Join(", ", new[] {
                        invoice.Customer?.Email,
                        invoice.Supplier?.Email
                    }.Where(e => !string.IsNullOrWhiteSpace(e)));

                    dbContext.InvoiceHistories.Add(new InvoiceHistory
                    {
                        InvoiceNo = invoice.InvoiceNo,
                        Action = "EmailSent",
                        PerformedBy = "Finalizer",
                        Remarks = invoice.ValidationEmailSentTo,
                        Timestamp = DateTime.UtcNow
                    });

                    result.EmailsSent++;
                    changesMade = true;
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"❌ Failed to send email for {invoice.InvoiceNo}");
                }
            }

            if (changesMade)
            {
                await dbContext.SaveChangesAsync();
            }
        }

        return result;
    }

    public async Task<string> RunManuallyAsync(
        ApplicationDbContext dbContext,
        IPdfGeneratorService pdfService,
        IEInvoiceNotificationService notificationService,
        string triggeredBy = "System")
    {
        dbContext.InvoiceHistories.Add(new InvoiceHistory
        {
            InvoiceNo = "SYSTEM",
            Action = "InvoiceFinalizeTriggered",
            PerformedBy = triggeredBy,
            Remarks = "Manual finalization run started.",
            Timestamp = DateTime.UtcNow
        });

        await dbContext.SaveChangesAsync();

        var result = await FinalizeInvoicesAsync(dbContext, pdfService, notificationService);

        return $"📄 PDFs generated: <strong>{result.PdfsGenerated}</strong><br/>" +
               $"📧 Emails sent: <strong>{result.EmailsSent}</strong>";
    }
}
